/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocios.ClsNegCargo;
import Entidad.ClsEnCargo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex_
 */
public class FrmCargo extends javax.swing.JPanel {

    /**
     * Creates new form FrmCargo
     */
    public FrmCargo() {
        initComponents();
        ClsNegCargo Ntabla = new ClsNegCargo();       
        DefaultTableModel modelo = Ntabla.ListarCargo();
        TblCargo.setModel(modelo);
        TxtIdCargo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGuardarCargo = new javax.swing.JButton();
        BtnModificarCargo = new javax.swing.JButton();
        TxtNombreCargo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCargo = new javax.swing.JTable();
        TxtIdCargo = new javax.swing.JTextField();
        ChbClinica = new javax.swing.JCheckBox();
        ChbUsuario = new javax.swing.JCheckBox();
        ChbCliente = new javax.swing.JCheckBox();
        ChbProducto = new javax.swing.JCheckBox();
        ChbInventario = new javax.swing.JCheckBox();
        ChbSpa = new javax.swing.JCheckBox();
        ChbReporte = new javax.swing.JCheckBox();
        ChbVenta = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(64, 69, 76));

        BtnGuardarCargo.setBackground(new java.awt.Color(4, 41, 68));
        BtnGuardarCargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnGuardarCargo.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarCargo.setText("Guardar");
        BtnGuardarCargo.setBorder(null);
        BtnGuardarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarCargoActionPerformed(evt);
            }
        });

        BtnModificarCargo.setBackground(new java.awt.Color(4, 41, 68));
        BtnModificarCargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnModificarCargo.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarCargo.setText("Modificar");
        BtnModificarCargo.setBorder(null);
        BtnModificarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarCargoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nombre");

        TblCargo.setBackground(new java.awt.Color(204, 204, 204));
        TblCargo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TblCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblCargo.getTableHeader().setReorderingAllowed(false);
        TblCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblCargoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblCargo);

        ChbClinica.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ChbClinica.setForeground(new java.awt.Color(0, 0, 0));
        ChbClinica.setText("Seccion Clinica");
        ChbClinica.setBorder(null);

        ChbUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ChbUsuario.setForeground(new java.awt.Color(0, 0, 0));
        ChbUsuario.setText("Seccion Usuario");
        ChbUsuario.setBorder(null);

        ChbCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ChbCliente.setForeground(new java.awt.Color(0, 0, 0));
        ChbCliente.setText("Seccion Cliente");
        ChbCliente.setBorder(null);

        ChbProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ChbProducto.setForeground(new java.awt.Color(0, 0, 0));
        ChbProducto.setText("Seccion Producto");
        ChbProducto.setBorder(null);

        ChbInventario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ChbInventario.setForeground(new java.awt.Color(0, 0, 0));
        ChbInventario.setText("Seccion Inventario");
        ChbInventario.setBorder(null);

        ChbSpa.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ChbSpa.setForeground(new java.awt.Color(0, 0, 0));
        ChbSpa.setText("Seccion Spa");
        ChbSpa.setBorder(null);

        ChbReporte.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ChbReporte.setForeground(new java.awt.Color(0, 0, 0));
        ChbReporte.setText("Seccion Reportes");
        ChbReporte.setBorder(null);

        ChbVenta.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ChbVenta.setForeground(new java.awt.Color(0, 0, 0));
        ChbVenta.setText("Seccion Venta");
        ChbVenta.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtIdCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(442, 442, 442)
                                .addComponent(BtnModificarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(341, 341, 341)
                                .addComponent(BtnGuardarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChbInventario)
                                    .addComponent(ChbClinica))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChbUsuario)
                                    .addComponent(ChbSpa))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChbCliente)
                                    .addComponent(ChbReporte))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChbProducto)
                                    .addComponent(ChbVenta)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(TxtNombreCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombreCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChbClinica, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChbUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChbProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChbCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChbSpa)
                    .addComponent(ChbInventario)
                    .addComponent(ChbReporte)
                    .addComponent(ChbVenta))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnModificarCargo)
                    .addComponent(BtnGuardarCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtIdCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarCargoActionPerformed
        // TODO add your handling code here:
        ClsEnCargo objEC = new ClsEnCargo();
        ClsNegCargo objNC = new ClsNegCargo();
        
        objEC.setNombre(TxtNombreCargo.getText());
        if(ChbProducto.isSelected()==true)
        {
            objEC.setFproducto("Activo");
        }
        else
        {
            objEC.setFproducto("Inactivo");
        }
        if(ChbClinica.isSelected()==true)
        {
            objEC.setFclinica("Activo");
        }
        else
        {
            objEC.setFclinica("Inactivo");
        }
        if(ChbInventario.isSelected()==true)
        {
            objEC.setFinventario("Activo");
        }
        else
        {
            objEC.setFinventario("Inactivo");
        }
        if(ChbReporte.isSelected()==true)
        {
            objEC.setFreporte("Activo");
        }
        else
        {
            objEC.setFreporte("Inactivo");
        }
        if(ChbUsuario.isSelected()==true)
        {
            objEC.setFusuario("Activo");
        }
        else
        {
            objEC.setFusuario("Inactivo");
        }
        if(ChbCliente.isSelected()==true)
        {
            objEC.setFcliente("Activo");
        }
        else
        {
            objEC.setFcliente("Inactivo");
        }
        if(ChbVenta.isSelected()==true)
        {
            objEC.setFventa("Activo");
        }
        else
        {
            objEC.setFventa("Inactivo");
        }
        if(ChbSpa.isSelected()==true)
        {
            objEC.setFspa("Activo");
        }
        else
        {
            objEC.setFspa("Inactivo");
        }
                
        if(objNC.MtdRegistrarCargo(objEC)==true)
        {
            JOptionPane.showMessageDialog(null,"Datos Guardados");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Error de Registro");
        }
        DefaultTableModel modelo = objNC.ListarCargo();
        TblCargo.setModel(modelo);
    }//GEN-LAST:event_BtnGuardarCargoActionPerformed

    private void BtnModificarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarCargoActionPerformed
        // TODO add your handling code here:
        ClsEnCargo objEC = new ClsEnCargo();
        ClsNegCargo objNC = new ClsNegCargo();
        objEC.setId(Integer.parseInt(TxtIdCargo.getText()));
        objEC.setNombre(TxtNombreCargo.getText());
        if(ChbProducto.isSelected()==true)
        {
            objEC.setFproducto("Activo");
        }
        else
        {
            objEC.setFproducto("Inactivo");
        }
        if(ChbClinica.isSelected()==true)
        {
            objEC.setFclinica("Activo");
        }
        else
        {
            objEC.setFclinica("Inactivo");
        }
        if(ChbInventario.isSelected()==true)
        {
            objEC.setFinventario("Activo");
        }
        else
        {
            objEC.setFinventario("Inactivo");
        }
        if(ChbReporte.isSelected()==true)
        {
            objEC.setFreporte("Activo");
        }
        else
        {
            objEC.setFreporte("Inactivo");
        }
        if(ChbUsuario.isSelected()==true)
        {
            objEC.setFusuario("Activo");
        }
        else
        {
            objEC.setFusuario("Inactivo");
        }
        if(ChbCliente.isSelected()==true)
        {
            objEC.setFcliente("Activo");
        }
        else
        {
            objEC.setFcliente("Inactivo");
        }
        if(ChbVenta.isSelected()==true)
        {
            objEC.setFventa("Activo");
        }
        else
        {
            objEC.setFventa("Inactivo");
        }
        if(ChbSpa.isSelected()==true)
        {
            objEC.setFspa("Activo");
        }
        else
        {
            objEC.setFspa("Inactivo");
        }
        if(objNC.MtdModificarCargo(objEC)==true)
        {
            JOptionPane.showMessageDialog(null,"Datos Modificados");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"ERROR DE REGISTRO");
        }
    }//GEN-LAST:event_BtnModificarCargoActionPerformed

    private void TblCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblCargoMouseClicked
        // TODO add your handling code here:
        int row=TblCargo.getSelectedRow();
        TxtIdCargo.setText(TblCargo.getValueAt(row,0).toString());
        TxtNombreCargo.setText(TblCargo.getValueAt(row,1).toString());
        if(TblCargo.getValueAt(row,2).toString().equals("Activo"))
        {
            ChbProducto.setSelected(true);
        }
        else
        {
            ChbProducto.setSelected(false);
        }
        if(TblCargo.getValueAt(row,3).toString().equals("Activo"))
        {
            ChbClinica.setSelected(true);
        }
        else
        {
            ChbClinica.setSelected(false);
        }
        if(TblCargo.getValueAt(row,4).toString().equals("Activo"))
        {
            ChbInventario.setSelected(true);
        }
        else
        {
            ChbInventario.setSelected(false);
        }
        if(TblCargo.getValueAt(row,5).toString().equals("Activo"))
        {
            ChbReporte.setSelected(true);
        }
        else
        {
            ChbReporte.setSelected(false);
        }
        if(TblCargo.getValueAt(row,6).toString().equals("Activo"))
        {
            ChbUsuario.setSelected(true);
        }
        else
        {
            ChbUsuario.setSelected(false);
        }
        if(TblCargo.getValueAt(row,7).toString().equals("Activo"))
        {
            ChbCliente.setSelected(true);
        }
        else
        {
            ChbCliente.setSelected(false);
        }
        if(TblCargo.getValueAt(row,8).toString().equals("Activo"))
        {
            ChbVenta.setSelected(true);
        }
        else
        {
            ChbVenta.setSelected(false);
        }
        if(TblCargo.getValueAt(row,9).toString().equals("Activo"))
        {
            ChbSpa.setSelected(true);
        }
        else
        {
            ChbSpa.setSelected(false);
        }
        

    }//GEN-LAST:event_TblCargoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardarCargo;
    private javax.swing.JButton BtnModificarCargo;
    private javax.swing.JCheckBox ChbCliente;
    private javax.swing.JCheckBox ChbClinica;
    private javax.swing.JCheckBox ChbInventario;
    private javax.swing.JCheckBox ChbProducto;
    private javax.swing.JCheckBox ChbReporte;
    private javax.swing.JCheckBox ChbSpa;
    private javax.swing.JCheckBox ChbUsuario;
    private javax.swing.JCheckBox ChbVenta;
    private javax.swing.JTable TblCargo;
    private javax.swing.JTextField TxtIdCargo;
    private javax.swing.JTextField TxtNombreCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
