/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.table.DefaultTableModel;
import Entidad.ClsEnEmpleado;
import Negocios.ClsNegCargo;
import Negocios.ClsNegEmpleado;
import static Presentacion.FrmPrincipal.PnlPrincipal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Alex_
 */
public class FrmEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form FrmEmpleados
     */
    public FrmEmpleados() {
        initComponents();
        ClsNegEmpleado Ntabla = new ClsNegEmpleado();       
        //DefaultTableModel modelo = Ntabla.ListarEmpleados();
        
        //DefaultTableModel modelo = new DefaultTableModel();
        //TblEmpleado.setModel(modelo);
        TblEmpleado.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
       // TblEmpleado.getTableHeader().setBackground(new Color(32,136,203));
       // TblEmpleado.getTableHeader().setForeground(new Color(32,136,203));
       TxtRuta.setVisible(false);
       LblFoto.setVisible(true);
       TxtId.setVisible(false);
       Ntabla.Listar_Cargos(CboCargo);
       Ntabla.visualizar_Empleado(TblEmpleado);
      //ClsNegCargo cargoo = new ClsNegCargo();
       //Ntabla.visualizar_Cbocargo(TblEmpleado);
       
    }
    //METODOS PARA EMPLEADO CON IMAGEN
    public void agregar(String nombre, String apellido, int dni, String telefono, String direccion, int idcargo, int codigo, String clave
            , String estado, File ruta){
        ClsEnEmpleado vo = new ClsEnEmpleado();
        ClsNegEmpleado dao = new ClsNegEmpleado();
        
        vo.setNombre(nombre);
        vo.setApellido(apellido);
        vo.setDni(dni);
        vo.setTelefono(telefono);
        vo.setDireccion(direccion);
        vo.setIdcargo(idcargo);
        vo.setCodigo(codigo);
        vo.setClave(clave);
        vo.setEstado(estado);
       
        try{
            byte[] icono = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(icono);
            vo.setFoto(icono);
        }catch(Exception ex){
            vo.setFoto(null);
        }
        dao.GuardarEmpleado(vo);
        
    }
    
     public void modificar(int id,String nombre, String apellido, int dni, String telefono, String direccion, int idcargo, int codigo, String clave
            , String estado, File ruta){
        ClsEnEmpleado vo = new ClsEnEmpleado();
        ClsNegEmpleado objNE = new ClsNegEmpleado();
        vo.setIdempleado(id);
        vo.setNombre(nombre);
        vo.setApellido(apellido);
        vo.setDni(dni);
        vo.setTelefono(telefono);
        vo.setDireccion(direccion);
        vo.setIdcargo(idcargo);
        vo.setCodigo(codigo);
        vo.setClave(clave);
        vo.setEstado(estado);
        try{
            byte[] icono = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(icono);
            vo.setFoto(icono);
        }catch(Exception ex){
            vo.setFoto(null);
        }
        objNE.Modificar_Empleado(vo);
    }
    
    public void modificar2(int id,String nombre, String apellido, int dni, String telefono, String direccion, int idcargo, int codigo, String clave
            , String estado){
        ClsEnEmpleado vo = new ClsEnEmpleado();
        ClsNegEmpleado objNE = new ClsNegEmpleado();
        vo.setIdempleado(id);
        vo.setNombre(nombre);
        vo.setApellido(apellido);
        vo.setDni(dni);
        vo.setTelefono(telefono);
        vo.setDireccion(direccion);
        vo.setIdcargo(idcargo);
        vo.setCodigo(codigo);
        vo.setClave(clave);
        vo.setEstado(estado);
        
        objNE.Modificar_Empleado2(vo);
    }
    
    /*public void eliminar(int id){
        ClsEnEmpleado vo = new ClsEnEmpleado();
        ClsNegEmpleado dao = new ClsNegEmpleado();
        
        vo.setIdproducto(codigo);
        
        dao.Eliminar_ProductoVO(vo);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtApellido = new javax.swing.JTextField();
        TxtDni = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtUsuario = new javax.swing.JTextField();
        TxtClave = new javax.swing.JTextField();
        LblFoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblEmpleado = new javax.swing.JTable();
        CboCargo = new javax.swing.JComboBox<>();
        BtnGuardarEmpleado = new javax.swing.JButton();
        BtnModificarEmpleado = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        CboEstado = new javax.swing.JComboBox<>();
        TxtRuta = new javax.swing.JTextField();
        TxtId = new javax.swing.JTextField();
        BtnAgregarCargo = new javax.swing.JButton();

        setBackground(new java.awt.Color(64, 69, 76));
        setMinimumSize(new java.awt.Dimension(890, 460));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 160, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Apellido");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Dni");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Telefono");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Direccion");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Cargo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Usuario");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Clave");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));
        add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, -1));
        add(TxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, -1));
        add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 160, -1));
        add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 160, -1));
        add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 120, -1));
        add(TxtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 120, -1));

        LblFoto.setText("         FOTO");
        LblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblFotoMouseClicked(evt);
            }
        });
        add(LblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 90, 110));

        TblEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        TblEmpleado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblEmpleado.getTableHeader().setReorderingAllowed(false);
        TblEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblEmpleado);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 760, 190));

        CboCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CboCargoMouseClicked(evt);
            }
        });
        CboCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboCargoActionPerformed(evt);
            }
        });
        add(CboCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 90, -1));

        BtnGuardarEmpleado.setBackground(new java.awt.Color(4, 41, 68));
        BtnGuardarEmpleado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnGuardarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardarEmpleado.setText("Guardar");
        BtnGuardarEmpleado.setBorder(null);
        BtnGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarEmpleadoActionPerformed(evt);
            }
        });
        add(BtnGuardarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 70, -1));

        BtnModificarEmpleado.setBackground(new java.awt.Color(4, 41, 68));
        BtnModificarEmpleado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnModificarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarEmpleado.setText("Modificar");
        BtnModificarEmpleado.setBorder(null);
        BtnModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarEmpleadoActionPerformed(evt);
            }
        });
        add(BtnModificarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 80, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Estado");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        CboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        add(CboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 120, -1));
        add(TxtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 90, -1));
        add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 70, -1));

        BtnAgregarCargo.setBackground(new java.awt.Color(4, 41, 68));
        BtnAgregarCargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnAgregarCargo.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregarCargo.setText("Crear Cargo");
        BtnAgregarCargo.setBorder(null);
        BtnAgregarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarCargoActionPerformed(evt);
            }
        });
        add(BtnAgregarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void LblFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFotoMouseClicked
        // TODO add your handling code here:
        
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        j.setFileFilter(fil);
        
        int s = j.showOpenDialog(this);
        if(s == JFileChooser.APPROVE_OPTION){
            String ruta = j.getSelectedFile().getAbsolutePath();
            TxtRuta.setText(ruta);
           Image miimagen = new ImageIcon(ruta).getImage();
           ImageIcon imgicon = new ImageIcon(miimagen.getScaledInstance(LblFoto.getWidth(),LblFoto.getHeight(),0));
           LblFoto.setIcon(imgicon);
        }
        
    }//GEN-LAST:event_LblFotoMouseClicked

    private void BtnGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarEmpleadoActionPerformed
        // TODO add your handling code here:
        ClsEnEmpleado objEE = new ClsEnEmpleado();
        ClsNegEmpleado objNE = new ClsNegEmpleado();
        /*
        objEE.setNombre(TxtNombre.getText());
        objEE.setApellido(TxtApellido.getText());
        objEE.setDni(Integer.parseInt(TxtDni.getText()));
        objEE.setTelefono(TxtTelefono.getText());
        objEE.setDireccion(TxtDireccion.getText());
        objEE.setIdcargo(CboCargo.getSelectedIndex());
        objEE.setCodigo(Integer.parseInt(TxtUsuario.getText()));
        objEE.setClave(TxtClave.getText());
        objEE.setEstado(CboEstado.getSelectedItem().toString());
        
        if(objNE.MtdRegistrarEmpleado(objEE)==true)
        {
            JOptionPane.showMessageDialog(null,"Datos Guardados");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"ERROR");
        }
        DefaultTableModel modelo = objNE.ListarEmpleados();
        TblEmpleado.setModel(modelo);
*/
        String nombre = TxtNombre.getText();
        String apellido = TxtApellido.getText();
        int dni= Integer.parseInt(TxtDni.getText());
        String telefono = TxtTelefono.getText();
        String direccion = TxtDireccion.getText();
        int idcargo = CboCargo.getSelectedIndex();
        int codigo = Integer.parseInt(TxtUsuario.getText());
        String clave = TxtClave.getText();
        String estado = CboEstado.getSelectedItem().toString();       
        File ruta = new File(TxtRuta.getText());
        
        this.agregar(nombre, apellido, dni,telefono,direccion,idcargo,codigo,clave,estado, ruta);
        objNE.visualizar_Empleado(TblEmpleado);
    }//GEN-LAST:event_BtnGuardarEmpleadoActionPerformed

    private void BtnModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarEmpleadoActionPerformed
        // TODO add your handling code here:
        ClsEnEmpleado objEE = new ClsEnEmpleado();
        ClsNegEmpleado objNE = new ClsNegEmpleado();
        /*objEE.setIdempleado(Integer.parseInt(TxtId.getText()));
        objEE.setNombre(TxtNombre.getText());
        objEE.setApellido(TxtApellido.getText());
        objEE.setDni(Integer.parseInt(TxtDni.getText()));
        objEE.setTelefono(TxtTelefono.getText());
        objEE.setDireccion(TxtDireccion.getText());
        objEE.setIdcargo(CboCargo.getSelectedIndex()+1);
        objEE.setCodigo(Integer.parseInt(TxtUsuario.getText()));
        objEE.setClave(TxtClave.getText());
        objEE.setEstado(CboEstado.getSelectedItem().toString());
        if(objNE.MtdModificarEmpleado(objEE)==true)
        {
            JOptionPane.showMessageDialog(null,"Datos Modificados");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"ERROR");
        }*/
        int id =Integer.parseInt(TxtId.getText());
        String nombre = TxtNombre.getText();
        String apellido = TxtApellido.getText();
        int dni= Integer.parseInt(TxtDni.getText());
        String telefono = TxtTelefono.getText();
        String direccion = TxtDireccion.getText();
        int idcargo = CboCargo.getSelectedIndex();
        int codigo = Integer.parseInt(TxtUsuario.getText());
        String clave = TxtClave.getText();
        String estado = CboEstado.getSelectedItem().toString();       
        File ruta = new File(TxtRuta.getText());
        
        if(TxtRuta.getText()!=null){
            this.modificar(id,nombre, apellido, dni,telefono,direccion,idcargo,codigo,clave,estado, ruta);
            objNE.visualizar_Empleado(TblEmpleado);
            
        }else{
            this.modificar2(id,nombre, apellido, dni,telefono,direccion,idcargo,codigo,clave,estado);
            objNE.visualizar_Empleado(TblEmpleado);
            
        }
    }//GEN-LAST:event_BtnModificarEmpleadoActionPerformed

    private void TblEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblEmpleadoMouseClicked
        // TODO add your handling code here:
        ClsEnEmpleado objEE = new ClsEnEmpleado();
        ClsNegEmpleado objNE = new ClsNegEmpleado();
        int row=TblEmpleado.getSelectedRow();
        TxtId.setText(TblEmpleado.getValueAt(row,0).toString());
        TxtNombre.setText(TblEmpleado.getValueAt(row,1).toString());
        TxtApellido.setText(TblEmpleado.getValueAt(row,2).toString());
        TxtDni.setText(TblEmpleado.getValueAt(row,3).toString());
        TxtTelefono.setText(TblEmpleado.getValueAt(row,4).toString());
        TxtDireccion.setText(TblEmpleado.getValueAt(row,5).toString());
        CboCargo.setSelectedItem(TblEmpleado.getValueAt(row,6).toString());
        TxtUsuario.setText(TblEmpleado.getValueAt(row,7).toString());
        TxtClave.setText(TblEmpleado.getValueAt(row,8).toString());
        CboEstado.setSelectedItem(TblEmpleado.getValueAt(row,9).toString());
        //TxtRuta.setText(TblEmpleado.getValueAt(row,10).toString());                   
    }//GEN-LAST:event_TblEmpleadoMouseClicked

    private void BtnAgregarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarCargoActionPerformed
        // TODO add your handling code here:
        FrmCargo frm = new FrmCargo();
        frm.setSize(890,460);
        frm.setLocation(190,40);       
        PnlPrincipal.removeAll();
        PnlPrincipal.add(frm, BorderLayout.CENTER);
        PnlPrincipal.revalidate();
        PnlPrincipal.repaint();
    }//GEN-LAST:event_BtnAgregarCargoActionPerformed

    private void CboCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboCargoActionPerformed
       
        
    }//GEN-LAST:event_CboCargoActionPerformed

    private void CboCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CboCargoMouseClicked
       /* ClsEnEmpleado objEE = new ClsEnEmpleado();
        ClsNegEmpleado objNE = new ClsNegEmpleado();
        int a = CboCargo.getSelectedIndex();
        TxtId.setText(TblEmpleado.getValueAt(a,0).toString());
        TxtNombre.setText(TblEmpleado.getValueAt(a,1).toString());
        TxtApellido.setText(TblEmpleado.getValueAt(a,2).toString());
        TxtDni.setText(TblEmpleado.getValueAt(a,3).toString());
        TxtTelefono.setText(TblEmpleado.getValueAt(a,4).toString());
        TxtDireccion.setText(TblEmpleado.getValueAt(a,5).toString());
        TxtUsuario.setText(TblEmpleado.getValueAt(a,7).toString());
        TxtClave.setText(TblEmpleado.getValueAt(a,8).toString());*/
    }//GEN-LAST:event_CboCargoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarCargo;
    private javax.swing.JButton BtnGuardarEmpleado;
    private javax.swing.JButton BtnModificarEmpleado;
    private javax.swing.JComboBox<String> CboCargo;
    private javax.swing.JComboBox<String> CboEstado;
    private javax.swing.JLabel LblFoto;
    private javax.swing.JTable TblEmpleado;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtClave;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtDni;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtRuta;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}



