/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.ClsEnEmpleado;
import Negocios.ClsLogin;
import Recursos.ClsHash;
import Recursos.TextPrompt;
import java.awt.Image;
import static java.util.Objects.hash;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Alex_
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        //Inicializamos la imagen de acuerdo al tamaño del objeto
        //Imagen de logo
        Icon i = LblLogo.getIcon();
        ImageIcon icon= (ImageIcon)i;
        Image ima = icon.getImage().getScaledInstance(LblLogo.getWidth(), LblLogo.getHeight(),Image.SCALE_SMOOTH);
        LblLogo.setIcon(new ImageIcon(ima));
        //Imagen de Usuario
        Icon j = LblUsuario.getIcon();
        ImageIcon jicon= (ImageIcon)j;
        Image imag = jicon.getImage().getScaledInstance(LblUsuario.getWidth(), LblUsuario.getHeight(),Image.SCALE_SMOOTH);
        LblUsuario.setIcon(new ImageIcon(imag));
        //Imagen de candado
        Icon k = LblClave.getIcon();
        ImageIcon kicon= (ImageIcon)k;
        Image image = kicon.getImage().getScaledInstance(LblClave.getWidth(), LblClave.getHeight(),Image.SCALE_SMOOTH);
        LblClave.setIcon(new ImageIcon(image));
        //Ubicamos al formulario en el centro
        this.setLocationRelativeTo(null);
        //Placeholder para usuario y clave
        TextPrompt usuario = new TextPrompt("  USUARIO",TxtUsuario);
        TextPrompt clave = new TextPrompt("  CONTRASEÑA",TxtClave);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblLogo = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnCerrar = new javax.swing.JButton();
        BtnMinimizar = new javax.swing.JButton();
        TxtClave = new javax.swing.JPasswordField();
        LblUsuario = new javax.swing.JLabel();
        LblClave = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo2.png"))); // NOI18N
        jPanel1.add(LblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 201, 270));

        TxtUsuario.setBackground(new java.awt.Color(15, 15, 15));
        TxtUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TxtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        TxtUsuario.setToolTipText("");
        TxtUsuario.setBorder(null);
        jPanel1.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 150, 30));

        jLabel1.setBackground(new java.awt.Color(15, 15, 15));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("  LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 30, 80, -1));

        BtnCerrar.setBackground(new java.awt.Color(15, 15, 15));
        BtnCerrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnCerrar.setForeground(new java.awt.Color(180, 180, 180));
        BtnCerrar.setText("X");
        BtnCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCerrar.setBorderPainted(false);
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 20, -1));

        BtnMinimizar.setBackground(new java.awt.Color(15, 15, 15));
        BtnMinimizar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnMinimizar.setForeground(new java.awt.Color(183, 183, 183));
        BtnMinimizar.setText("_");
        BtnMinimizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMinimizar.setBorderPainted(false);
        BtnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 20, -1));

        TxtClave.setBackground(new java.awt.Color(15, 15, 15));
        TxtClave.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TxtClave.setForeground(new java.awt.Color(153, 153, 153));
        TxtClave.setBorder(null);
        jPanel1.add(TxtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 150, 30));

        LblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario.png"))); // NOI18N
        jPanel1.add(LblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 30, 30));

        LblClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/padlock.png"))); // NOI18N
        jPanel1.add(LblClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 30, 30));

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("___________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 170, 20));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("___________________________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 170, 20));

        BtnIngresar.setBackground(new java.awt.Color(0, 153, 255));
        BtnIngresar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnIngresar.setText("INGRESAR");
        BtnIngresar.setBorder(null);
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 215, 140, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 503, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void BtnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinimizarActionPerformed
        // TODO add your handling code here:
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_BtnMinimizarActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
        
        ClsEnEmpleado emp = new ClsEnEmpleado();
        ClsLogin log = new ClsLogin();
        String clav= new String(TxtClave.getText());
        String est= new String("Activo");
        if(!TxtUsuario.getText().equals("") && !clav.equals("") && !est.equals(""))
        {
            String nuevaclav = ClsHash.sha1(clav);
            emp.setCodigo(Integer.parseInt(TxtUsuario.getText()));
            emp.setClave(TxtClave.getText());
            emp.setEstado("Activo");
            if(log.Login(emp))
            {
               FrmPrincipal frm = new FrmPrincipal(emp);
               frm.show();
               this.hide();
               //frm.BtnUsuarios.setEnabled(false);
               
               
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Erro de Inicio de Sesion, para mas Informacion Consulte con el Administrador");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Ingrese todos los datos");
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnMinimizar;
    private javax.swing.JLabel LblClave;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JPasswordField TxtClave;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
