/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.ClsEnEmpleado;
import java.awt.BorderLayout;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Alex_
 */
public class FrmPrincipal extends javax.swing.JFrame implements Runnable{
      String hora,minutos,segundos,ampm;
      Calendar calendario;
      Thread h1;
      ClsEnEmpleado emp;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
          //seccion iconos   
              
    }
   public FrmPrincipal(ClsEnEmpleado emp)
       {
           
           initComponents();
           //setLocationRelativeTo(null);
           this.emp=emp;
           LblUsuario.setText(String.valueOf(emp.codigo));
           LblNombre.setText(String.valueOf(emp.getNombre()));
           LblCargo.setText(String.valueOf(emp.getNombrecargo()));
           if(emp.getFproductocargo().equals("Activo"))
           {
               BtnProductos.setEnabled(true);
           }
           else{
               BtnProductos.setEnabled(false);
           }
           if(emp.getFclientecargo().equals("Activo"))
           {
               BtnCliente.setEnabled(true);
           }
           else{
               BtnCliente.setEnabled(false);
           }
           if(emp.getFclinicacargo().equals("Activo"))
           {
               BtnClinica.setEnabled(true);
           }
           else{
               BtnClinica.setEnabled(false);
           }
           if(emp.getFinventariocargo().equals("Activo"))
           {
               BtnInventario.setEnabled(true);
           }
           else{
               BtnInventario.setEnabled(false);
           }
           if(emp.getFreportecargo().equals("Activo"))
           {
               BtnReportes.setEnabled(true);
           }
           else{
               BtnReportes.setEnabled(false);
           }
           if(emp.getFspacargo().equals("Activo"))
           {
               BtnSpa.setEnabled(true);
           }
           else{
               BtnSpa.setEnabled(false);
           }
           if(emp.getFusuariocargo().equals("Activo"))
           {
               BtnUsuarios.setEnabled(true);
           }
           else{
               BtnUsuarios.setEnabled(false);
           }
           if(emp.getFventacargo().equals("Activo"))
           {
               BtnVentas.setEnabled(true);
           }
           else{
               BtnVentas.setEnabled(false);
           }
          
           Icon i = LblPresentacion.getIcon();
        ImageIcon icon= (ImageIcon)i;
        Image ima = icon.getImage().getScaledInstance(LblPresentacion.getWidth(), LblPresentacion.getHeight(),Image.SCALE_SMOOTH);
        LblPresentacion.setIcon(new ImageIcon(ima));
        
        Icon j = LblInicial.getIcon();
        ImageIcon ico= (ImageIcon)j;
        Image imag = ico.getImage().getScaledInstance(LblInicial.getWidth(), LblInicial.getHeight(),Image.SCALE_SMOOTH);
        LblInicial.setIcon(new ImageIcon(imag));
        //seccion hora fecha
        this.setLocationRelativeTo(null);
        String dia="";
        //LocalTime hora = LocalTime.now();
        //LblHora.setText(String.valueOf(hora.getHour()+":"+hora.getMinute()+":"+hora.getSecond()));
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMMM-YYYY");
        Date fecha = new Date();
        if(fecha.getDay()== 1)
            dia="Lunes";
        else if(fecha.getDay()==2)
            dia="Martes";
        else if(fecha.getDay()==3)
            dia="Miercoles";
        else if(fecha.getDay()==4)
            dia="Jueves";
        else if(fecha.getDay()==5)
            dia="Viernes";
        else if(fecha.getDay()==6)
            dia="Sabado";
        else if(fecha.getDay()==7)
            dia="Domingo";
        LblFecha.setText(String.valueOf(dia+" "+sdf.format(fecha)));
        
       h1 = new Thread(this);
       h1.start();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnUsuarios = new javax.swing.JButton();
        BtnCliente = new javax.swing.JButton();
        BtnClinica = new javax.swing.JButton();
        BtnVentas = new javax.swing.JButton();
        BtnSpa = new javax.swing.JButton();
        BtnProductos = new javax.swing.JButton();
        BtnInventario = new javax.swing.JButton();
        BtnReportes = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LblPresentacion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LblMinimizar = new javax.swing.JLabel();
        LblCerrar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LblUsuario = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblCargo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LblHora = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        PnlPrincipal = new javax.swing.JPanel();
        LblInicial = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1080, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(4, 41, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnUsuarios.setBackground(new java.awt.Color(4, 41, 68));
        BtnUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BtnUsuarios.setForeground(new java.awt.Color(204, 204, 204));
        BtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/person-settings1.png"))); // NOI18N
        BtnUsuarios.setText("USUARIOS");
        BtnUsuarios.setBorder(null);
        BtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(BtnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, -1));

        BtnCliente.setBackground(new java.awt.Color(4, 41, 68));
        BtnCliente.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BtnCliente.setForeground(new java.awt.Color(204, 204, 204));
        BtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/phone-book (1)1.png"))); // NOI18N
        BtnCliente.setText("CLIENTE");
        BtnCliente.setBorder(null);
        BtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClienteActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, -1));

        BtnClinica.setBackground(new java.awt.Color(4, 41, 68));
        BtnClinica.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BtnClinica.setForeground(new java.awt.Color(204, 204, 204));
        BtnClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/health (1)1.png"))); // NOI18N
        BtnClinica.setText("CLINICA");
        BtnClinica.setBorder(null);
        BtnClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClinicaActionPerformed(evt);
            }
        });
        jPanel2.add(BtnClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, -1));

        BtnVentas.setBackground(new java.awt.Color(4, 41, 68));
        BtnVentas.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BtnVentas.setForeground(new java.awt.Color(204, 204, 204));
        BtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/payment1.png"))); // NOI18N
        BtnVentas.setText("VENTAS");
        BtnVentas.setBorder(null);
        BtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasActionPerformed(evt);
            }
        });
        jPanel2.add(BtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, -1));

        BtnSpa.setBackground(new java.awt.Color(4, 41, 68));
        BtnSpa.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BtnSpa.setForeground(new java.awt.Color(204, 204, 204));
        BtnSpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/phone-book (1)1.png"))); // NOI18N
        BtnSpa.setText("SPA");
        BtnSpa.setBorder(null);
        BtnSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSpaActionPerformed(evt);
            }
        });
        jPanel2.add(BtnSpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 220, 170, -1));

        BtnProductos.setBackground(new java.awt.Color(4, 41, 68));
        BtnProductos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BtnProductos.setForeground(new java.awt.Color(204, 204, 204));
        BtnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/person-settings1.png"))); // NOI18N
        BtnProductos.setText("PRODUCTOS");
        BtnProductos.setBorder(null);
        BtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProductosActionPerformed(evt);
            }
        });
        jPanel2.add(BtnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, -1));

        BtnInventario.setBackground(new java.awt.Color(4, 41, 68));
        BtnInventario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BtnInventario.setForeground(new java.awt.Color(204, 204, 204));
        BtnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/calendar (1)1.png"))); // NOI18N
        BtnInventario.setText("INVENTARIO");
        BtnInventario.setBorder(null);
        BtnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInventarioActionPerformed(evt);
            }
        });
        jPanel2.add(BtnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 170, -1));

        BtnReportes.setBackground(new java.awt.Color(4, 41, 68));
        BtnReportes.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        BtnReportes.setForeground(new java.awt.Color(204, 204, 204));
        BtnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bar-graph1.png"))); // NOI18N
        BtnReportes.setText("REPORTES");
        BtnReportes.setBorder(null);
        BtnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReportesActionPerformed(evt);
            }
        });
        jPanel2.add(BtnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 170, -1));

        BtnSalir.setBackground(new java.awt.Color(4, 41, 68));
        BtnSalir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(204, 204, 204));
        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logout (1)1.png"))); // NOI18N
        BtnSalir.setText("SALIR");
        BtnSalir.setBorder(null);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 560));

        jPanel1.setBackground(new java.awt.Color(13, 93, 142));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblPresentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo2.png"))); // NOI18N
        jPanel1.add(LblPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ROYAL VET");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        LblMinimizar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LblMinimizar.setForeground(new java.awt.Color(204, 204, 204));
        LblMinimizar.setText("_");
        LblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(LblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, -1, -1));

        LblCerrar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LblCerrar.setForeground(new java.awt.Color(204, 204, 204));
        LblCerrar.setText("x");
        LblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(LblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        jPanel4.setBackground(new java.awt.Color(13, 93, 142));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblUsuario.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LblUsuario.setText("USUARIO");
        jPanel4.add(LblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        LblNombre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LblNombre.setForeground(new java.awt.Color(255, 255, 255));
        LblNombre.setText("NOMBRE Y APELLIDOS");
        jPanel4.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        LblCargo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LblCargo.setForeground(new java.awt.Color(255, 255, 255));
        LblCargo.setText("CARGO");
        jPanel4.add(LblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 80));

        LblHora.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        LblHora.setForeground(new java.awt.Color(255, 255, 255));
        LblHora.setText("00:00:00");
        jPanel4.add(LblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, 30));

        LblFecha.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        LblFecha.setForeground(new java.awt.Color(255, 255, 255));
        LblFecha.setText("LUNES 1 DE ENERO DEL 2021");
        jPanel4.add(LblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 890, 100));

        PnlPrincipal.setLayout(new java.awt.BorderLayout());

        LblInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/gatologo.jpg"))); // NOI18N
        PnlPrincipal.add(LblInicial, java.awt.BorderLayout.CENTER);

        getContentPane().add(PnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 890, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LblCerrarMouseClicked

    private void LblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblMinimizarMouseClicked
        // TODO add your handling code here:
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_LblMinimizarMouseClicked

    private void BtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuariosActionPerformed
        // TODO add your handling code here:
        FrmEmpleados frm = new FrmEmpleados();
        frm.setSize(890,460);
        frm.setLocation(190,40);
        
        PnlPrincipal.removeAll();
        PnlPrincipal.add(frm, BorderLayout.CENTER);
        PnlPrincipal.revalidate();
        PnlPrincipal.repaint();
    }//GEN-LAST:event_BtnUsuariosActionPerformed

    private void BtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClienteActionPerformed
        // TODO add your handling code here:
        FrmCliente frm = new FrmCliente();
        frm.setSize(890,460);
        frm.setLocation(190,40);
        
        PnlPrincipal.removeAll();
        PnlPrincipal.add(frm, BorderLayout.CENTER);
        PnlPrincipal.revalidate();
        PnlPrincipal.repaint();
    }//GEN-LAST:event_BtnClienteActionPerformed

    private void BtnClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClinicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnClinicaActionPerformed

    private void BtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasActionPerformed
        // TODO add your handling code here:
        FrmVentas frm = new FrmVentas();
        frm.setSize(890,460);
        frm.setLocation(190,40);
        
        PnlPrincipal.removeAll();
        PnlPrincipal.add(frm, BorderLayout.CENTER);
        PnlPrincipal.revalidate();
        PnlPrincipal.repaint();
    }//GEN-LAST:event_BtnVentasActionPerformed

    private void BtnSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSpaActionPerformed

    private void BtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProductosActionPerformed
        // TODO add your handling code here:
        FrmProductos frm = new FrmProductos();
        frm.setSize(890,460);
        frm.setLocation(190,40);
        
        PnlPrincipal.removeAll();
        PnlPrincipal.add(frm, BorderLayout.CENTER);
        PnlPrincipal.revalidate();
        PnlPrincipal.repaint();
    }//GEN-LAST:event_BtnProductosActionPerformed

    private void BtnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInventarioActionPerformed

    private void BtnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnReportesActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        FrmLogin frm = new FrmLogin();
        frm.show();
        this.hide();
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BtnCliente;
    public static javax.swing.JButton BtnClinica;
    public static javax.swing.JButton BtnInventario;
    public static javax.swing.JButton BtnProductos;
    public static javax.swing.JButton BtnReportes;
    private javax.swing.JButton BtnSalir;
    public static javax.swing.JButton BtnSpa;
    public static javax.swing.JButton BtnUsuarios;
    public static javax.swing.JButton BtnVentas;
    private javax.swing.JLabel LblCargo;
    private javax.swing.JLabel LblCerrar;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblHora;
    private javax.swing.JLabel LblInicial;
    private javax.swing.JLabel LblMinimizar;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblPresentacion;
    private javax.swing.JLabel LblUsuario;
    public static javax.swing.JPanel PnlPrincipal;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
       Thread ct = Thread.currentThread();
       while(ct==h1)
       {
           calcula();
           LblHora.setText(hora+":"+minutos+":"+segundos);
           try{
               Thread.sleep(1000);
           }catch(InterruptedException e){
               
           }
       }
    }

    private void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date horaActual = new Date();
        calendario.setTime(horaActual);
        ampm=calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        if(ampm.equals("PM"))
        {
            int h=calendario.get(Calendar.HOUR_OF_DAY)-12;
            hora = h>9?""+h:"0"+h;
        }
        else
        {
            hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    
    
}
