/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Alex_
 */
public class FrmProductos extends javax.swing.JPanel {

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblBoleta = new javax.swing.JTable();
        BtnGuardar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        TxtNombre = new javax.swing.JTextField();
        TxtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtPrecio = new javax.swing.JTextField();
        TxtMarca = new javax.swing.JTextField();
        TxtFechaExpira = new javax.swing.JTextField();
        TxtFechaIngreso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtCantidadCom = new javax.swing.JTextField();
        TxtFechaSal = new javax.swing.JTextField();
        TxtCantidadSal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtCantidadAc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(64, 69, 76));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnNuevo.setBackground(new java.awt.Color(4, 41, 68));
        BtnNuevo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        BtnNuevo.setText("Nuevo");
        BtnNuevo.setBorder(null);
        add(BtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 70, -1));

        TblBoleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblBoleta);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 760, 140));

        BtnGuardar.setBackground(new java.awt.Color(4, 41, 68));
        BtnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.setBorder(null);
        add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 70, -1));

        BtnModificar.setBackground(new java.awt.Color(4, 41, 68));
        BtnModificar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificar.setText("Modifcar");
        BtnModificar.setBorder(null);
        add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 70, -1));
        add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 122, -1));
        add(TxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 122, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Codigo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Nombre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Marca");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Precio");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));
        add(TxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 120, -1));
        add(TxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 122, -1));
        add(TxtFechaExpira, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 122, -1));
        add(TxtFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 122, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Fecha Ingreso");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Fecha Expira");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Fecha Salida");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Cantidad Comprada");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));
        add(TxtCantidadCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 120, -1));
        add(TxtFechaSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 122, -1));
        add(TxtCantidadSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 120, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Cantidad Salida");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));
        add(TxtCantidadAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Cantidad Actual");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JTable TblBoleta;
    private javax.swing.JTextField TxtCantidadAc;
    private javax.swing.JTextField TxtCantidadCom;
    private javax.swing.JTextField TxtCantidadSal;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtFechaExpira;
    private javax.swing.JTextField TxtFechaIngreso;
    private javax.swing.JTextField TxtFechaSal;
    private javax.swing.JTextField TxtMarca;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
