/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Alex_
 */
public class FrmVentas extends javax.swing.JPanel {

    /**
     * Creates new form FrmVentas
     */
    public FrmVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblProducto = new javax.swing.JTable();
        BtnGuardar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        TxtDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtDni1 = new javax.swing.JTextField();
        TxtNombre1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtTelefono1 = new javax.swing.JTextField();
        TxtDireccion1 = new javax.swing.JTextField();
        TxtTelefono2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtTelefono3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CboServicio = new javax.swing.JComboBox<>();
        BtnBoleta = new javax.swing.JButton();

        setBackground(new java.awt.Color(64, 69, 76));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnNuevo.setBackground(new java.awt.Color(4, 41, 68));
        BtnNuevo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        BtnNuevo.setText("Nuevo");
        BtnNuevo.setBorder(null);
        add(BtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 70, -1));

        TblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblProducto);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 760, 140));

        BtnGuardar.setBackground(new java.awt.Color(4, 41, 68));
        BtnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("Agregar");
        BtnGuardar.setBorder(null);
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 70, -1));

        BtnModificar.setBackground(new java.awt.Color(4, 41, 68));
        BtnModificar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificar.setText("Modifcar");
        BtnModificar.setBorder(null);
        add(BtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 70, -1));
        add(TxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 122, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Servicio");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        Cantidad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(204, 204, 204));
        Cantidad.setText("Cantidad");
        add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Descripcion");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("SubTotal");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 120, -1));
        add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 122, -1));
        add(TxtDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 122, -1));
        add(TxtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 60, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Igv");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Total");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Estado");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("id_Producto");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));
        add(TxtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 120, -1));
        add(TxtDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 122, -1));
        add(TxtTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 120, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Id_Empleado");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));
        add(TxtTelefono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Fecha");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 20));

        CboServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spa", "Venta Producto", "Clinica" }));
        add(CboServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, -1));

        BtnBoleta.setBackground(new java.awt.Color(4, 41, 68));
        BtnBoleta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BtnBoleta.setForeground(new java.awt.Color(255, 255, 255));
        BtnBoleta.setText("Generar Boleta");
        BtnBoleta.setBorder(null);
        BtnBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBoletaActionPerformed(evt);
            }
        });
        add(BtnBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBoletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBoletaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBoleta;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JComboBox<String> CboServicio;
    private javax.swing.JTable TblProducto;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtDireccion1;
    private javax.swing.JTextField TxtDni;
    private javax.swing.JTextField TxtDni1;
    private javax.swing.JTextField TxtNombre1;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JTextField TxtTelefono1;
    private javax.swing.JTextField TxtTelefono2;
    private javax.swing.JTextField TxtTelefono3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
